# Generated by Django 6.0.8 on 2026-09-25 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserLoginThrottleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[("source", "Source"), ("username", "Username")],
                        max_length=16,
                    ),
                ),
                ("bucket_key", models.CharField(max_length=64)),
                ("slot", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bucket_type", "bucket_key", "expires_at"],
                        name="acct_login_bucket_exp_idx",
                    ),
                    models.Index(fields=["expires_at"], name="acct_login_exp_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_type", "bucket_key", "slot"),
                        name="unique_browser_login_throttle_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientLoginRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(db_index=True, max_length=64)),
                ("client_name", models.CharField(max_length=200)),
                ("client_type", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("request_user_agent", models.CharField(blank=True, max_length=256)),
                (
                    "request_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "request_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Retained only while pending for outstanding-request limits and cleared on terminal transitions.",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_client_login_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserClientSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("client_type", models.CharField(max_length=64)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("librarian", "Librarian"),
                            ("reader", "Reader"),
                        ],
                        default="reader",
                        max_length=16,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                (
                    "web_session_generation",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "external_subject_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserWebSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientPairingThrottleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[("source", "Source"), ("fingerprint", "Fingerprint")],
                        max_length=16,
                    ),
                ),
                ("bucket_key", models.CharField(max_length=64)),
                ("slot", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
                (
                    "login_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="throttle_slots",
                        to="accounts.clientloginrequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bucket_type", "bucket_key", "expires_at"],
                        name="acct_pair_bucket_exp_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_type", "bucket_key", "slot"),
                        name="unique_pairing_throttle_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=100)),
                ("issuer", models.URLField(max_length=500)),
                ("subject", models.CharField(max_length=255)),
                ("email_at_login", models.EmailField(blank=True, max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                ("selected_claims", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "issuer", "subject"],
                "indexes": [
                    models.Index(
                        fields=["provider", "subject"],
                        name="acct_ext_provider_subj_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"),
                        name="unique_external_identity_issuer_subject",
                    )
                ],
            },
        ),
    ]
