# Generated by Django 6.0.7 on 2026-08-03 19:55

import hashlib
import unicodedata

from django.db import migrations, models


def bound_pairing_metadata(apps, schema_editor):
    ClientLoginRequest = apps.get_model("accounts", "ClientLoginRequest")
    updates = []
    for login_request in ClientLoginRequest.objects.all().iterator(chunk_size=500):
        is_pending = login_request.status == "pending"
        user_agent = (
            (login_request.request_user_agent or "")[:256] if is_pending else ""
        )
        material = "\0".join(
            (
                " ".join(
                    unicodedata.normalize("NFKC", login_request.client_name)
                    .casefold()
                    .split()
                ),
                " ".join(
                    unicodedata.normalize("NFKC", login_request.client_type)
                    .casefold()
                    .split()
                ),
                user_agent,
            )
        )
        login_request.request_user_agent = user_agent
        login_request.request_fingerprint = (
            hashlib.sha256(material.encode("utf-8")).hexdigest()
            if is_pending
            else ""
        )
        if not is_pending:
            login_request.request_ip = None
        updates.append(login_request)
        if len(updates) == 500:
            ClientLoginRequest.objects.bulk_update(
                updates,
                ["request_user_agent", "request_fingerprint", "request_ip"],
            )
            updates.clear()
    if updates:
        ClientLoginRequest.objects.bulk_update(
            updates,
            ["request_user_agent", "request_fingerprint", "request_ip"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloginrequest',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(bound_pairing_metadata, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clientloginrequest',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Retained only while pending for outstanding-request limits and cleared on terminal transitions.', null=True),
        ),
        migrations.AlterField(
            model_name='clientloginrequest',
            name='request_user_agent',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
