# Generated by Django 6.0.7 on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_bound_client_pairing_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPairingThrottleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[("source", "Source"), ("fingerprint", "Fingerprint")],
                        max_length=16,
                    ),
                ),
                ("bucket_key", models.CharField(max_length=64)),
                ("slot", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
                (
                    "login_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="throttle_slots",
                        to="accounts.clientloginrequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bucket_type", "bucket_key", "expires_at"],
                        name="acct_pair_bucket_exp_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_type", "bucket_key", "slot"),
                        name="unique_pairing_throttle_slot",
                    )
                ],
            },
        ),
    ]
