# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_clientpairingthrottleslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserLoginThrottleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[("source", "Source"), ("username", "Username")],
                        max_length=16,
                    ),
                ),
                ("bucket_key", models.CharField(max_length=64)),
                ("slot", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bucket_type", "bucket_key", "expires_at"],
                        name="acct_login_bucket_exp_idx",
                    ),
                    models.Index(fields=["expires_at"], name="acct_login_exp_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_type", "bucket_key", "slot"),
                        name="unique_browser_login_throttle_slot",
                    )
                ],
            },
        ),
    ]
