from __future__ import annotations

from collections.abc import Iterable


# Marker ownership is centralized so the supported lanes can be reviewed without
# scattering organization-only decorators through behavior tests. Prefixes end in
# '/' and exact files include the .py suffix.
_PATH_MARKERS: dict[str, tuple[str, ...]] = {
    "security": (
        "tests/accounts/client_api/",
        "tests/accounts/passwords/",
        "tests/accounts/web_sessions/",
        "tests/accounts/users/api/test_mutations.py",
        "tests/accounts/users/api/test_permissions.py",
        "tests/accounts/users/api/test_visibility.py",
        "tests/accounts/test_admin_role_restrictions.py",
        "tests/accounts/test_basic_auth_disabled.py",
        "tests/accounts/test_browser_auth.py",
        "tests/accounts/client_sessions/test_api.py",
        "tests/accounts/test_first_run_setup.py",
        "tests/accounts/test_first_run_setup_concurrency.py",
        "tests/core/test_admin_advanced_groups_recovery.py",
        "tests/core/test_admin_url_gating.py",
        "tests/core/test_api_route_errors.py",
        "tests/core/test_cors.py",
        "tests/core/test_media_serving.py",
        "tests/library/bearer/",
        "tests/library/catalog/test_book_download.py",
        "tests/library/catalog/test_bookverse_search.py",
        "tests/library/groups/test_book_assignment_create.py",
        "tests/library/groups/test_book_assignment_delete.py",
        "tests/library/groups/test_consolidation.py",
        "tests/library/groups/test_disabled_mode_api.py",
        "tests/library/groups/test_membership_create.py",
        "tests/library/groups/test_membership_delete.py",
        "tests/library/groups/test_membership_list.py",
        "tests/library/groups/test_membership_patch.py",
        "tests/library/groups/test_membership_public.py",
        "tests/library/groups/test_service_book_assignments.py",
        "tests/library/groups/test_service_delete_fallback.py",
        "tests/library/groups/test_service_locking.py",
        "tests/library/groups/test_service_memberships.py",
        "tests/library/groups/test_service_public.py",
        "tests/library/imports/test_archives.py",
        "tests/library/imports/test_cover_safety.py",
        "tests/library/imports/test_epub_archive_safety.py",
        "tests/library/imports/test_upload_api_auth_validation.py",
        "tests/library/imports/test_upload_api_boundaries.py",
        "tests/library/test_file_repair.py",
        "tests/library/test_queries.py",
        "tests/marginalia/annotations/test_batch_api.py",
        "tests/marginalia/annotations/test_read_api.py",
        "tests/marginalia/books/test_api.py",
        "tests/marginalia/sessions/test_book_api.py",
        "tests/marginalia/sessions/test_open_api.py",
        "tests/marginalia/sessions/test_start_over_api.py",
        "tests/marginalia/exports/test_api.py",
        "tests/marginalia/test_foundation.py",
        "tests/marginalia/imports/test_apply_api.py",
        "tests/marginalia/imports/test_preview_api.py",
        "tests/marginalia/imports/test_staging.py",
        "tests/marginalia/imports/test_unmatched_api.py",
        "tests/marginalia/sessions/test_progress_close_api.py",
        "tests/marginalia/sessions/test_detail_api.py",
        "tests/marginalia/sessions/test_list_api.py",
        "tests/shelves/api/test_library_rewrite_visibility.py",
        "tests/shelves/api/test_permissions.py",
        "tests/shelves/api/test_write_contract.py",
        "tests/shelves/bearer/",
        "tests/shelves/test_cleanup_shelves.py",
        "tests/shelves/test_group_removal_hook.py",
        "tests/shelves/test_service_authorization.py",
        "tests/shelves/test_service_items.py",
    ),
    "filesystem": (
        "tests/core/product_ui/test_react_app_routes.py",
        "tests/core/test_health.py",
        "tests/core/test_media_serving.py",
        "tests/core/test_release_metadata.py",
        "tests/core/test_static_files.py",
        "tests/library/catalog/test_book_covers.py",
        "tests/library/catalog/test_book_download.py",
        "tests/library/imports/test_archives.py",
        "tests/library/imports/test_cover_discovery.py",
        "tests/library/imports/test_cover_import_integration.py",
        "tests/library/imports/test_cover_safety.py",
        "tests/library/imports/test_epub.py",
        "tests/library/imports/test_epub_archive_safety.py",
        "tests/library/imports/test_import_library_commands.py",
        "tests/library/imports/test_operational_logging.py",
        "tests/library/imports/test_service_public_file.py",
        "tests/library/imports/test_upload_api_auth_validation.py",
        "tests/library/imports/test_upload_api_boundaries.py",
        "tests/library/imports/test_upload_api_results.py",
        "tests/library/imports/test_zip_import.py",
        "tests/library/imports/test_zip_sidecar_covers.py",
        "tests/library/imports/test_zip_sidecar_matching.py",
        "tests/library/imports/test_zip_sidecar_metadata.py",
        "tests/library/test_admin_file_repair.py",
        "tests/library/test_file_repair.py",
        "tests/marginalia/test_admin.py",
        "tests/marginalia/archives/test_serialization.py",
        "tests/marginalia/test_archive_spec_contract.py",
        "tests/marginalia/archives/test_validation.py",
        "tests/marginalia/exports/test_api.py",
        "tests/marginalia/imports/test_apply_api.py",
        "tests/marginalia/imports/test_preview_api.py",
        "tests/marginalia/imports/test_staging.py",
        "tests/marginalia/imports/test_unmatched_api.py",
        "tests/testenv/test_filesystem.py",
    ),
    "integration": (
        "tests/accounts/management/",
        "tests/accounts/test_admin_role_restrictions.py",
        "tests/core/product_ui/",
        "tests/core/test_admin_advanced_groups_recovery.py",
        "tests/core/test_admin_url_gating.py",
        "tests/core/test_health.py",
        "tests/core/test_media_serving.py",
        "tests/core/test_static_files.py",
        "tests/library/imports/test_cover_import_integration.py",
        "tests/library/imports/test_import_library_commands.py",
        "tests/library/imports/test_upload_api_auth_validation.py",
        "tests/library/imports/test_upload_api_boundaries.py",
        "tests/library/imports/test_upload_api_results.py",
        "tests/library/test_admin_book_changelist.py",
        "tests/library/test_admin_book_layout.py",
        "tests/library/test_admin_catalog_tag.py",
        "tests/library/test_admin_file_repair.py",
        "tests/marginalia/test_admin.py",
        "tests/marginalia/annotations/test_deleted_cleanup.py",
        "tests/marginalia/exports/test_api.py",
        "tests/marginalia/imports/test_apply_api.py",
        "tests/marginalia/imports/test_preview_api.py",
        "tests/marginalia/imports/test_staging.py",
        "tests/marginalia/imports/test_unmatched_api.py",
        "tests/shelves/test_admin_safety.py",
        "tests/shelves/test_cleanup_shelves.py",
    ),
}

_NODE_MARKERS: dict[str, tuple[str, ...]] = {
    "concurrency": (
        "tests/accounts/client_api/test_pairing_limits.py::PairingRequestLimitConcurrencyTests::",
        "tests/accounts/client_api/test_pairing_lifecycle.py::PairingConsumptionConcurrencyTests::",
        "tests/accounts/client_api/test_proxy_boundary.py::UvicornProxyBoundaryTests::",
        "tests/accounts/test_browser_auth.py::ConcurrentBrowserLoginThrottleTests::",
        "tests/accounts/test_first_run_setup_concurrency.py::FirstOwnerSetupConcurrencyTests::",
        "tests/marginalia/imports/test_apply_api.py::MarginaliaImportApplyConcurrencyTests::",
    ),
    "subprocess": (
        "tests/accounts/client_api/test_proxy_boundary.py::UvicornProxyBoundaryTests::",
        "tests/core/test_django_settings.py::DjangoSettingsContractTests::test_production_",
    ),
    "slow": (
        "tests/accounts/client_api/test_pairing_limits.py::PairingRequestLimitConcurrencyTests::",
        "tests/accounts/client_api/test_pairing_lifecycle.py::PairingConsumptionConcurrencyTests::",
        "tests/accounts/client_api/test_proxy_boundary.py::UvicornProxyBoundaryTests::",
        "tests/accounts/test_browser_auth.py::BrowserLoginThrottleTests::",
        "tests/accounts/test_browser_auth.py::ConcurrentBrowserLoginThrottleTests::",
        "tests/accounts/test_first_run_setup_concurrency.py::FirstOwnerSetupConcurrencyTests::",
        "tests/accounts/test_operational_logging.py::AccountOperationalLoggingTests::",
        "tests/accounts/users/api/test_choices.py::UserChoiceApiTests::",
        "tests/accounts/users/api/test_list_query.py::ManagedUsersListQueryAPITest::",
        "tests/accounts/users/api/test_mutations.py::ManagedUsersMutationsAPITest::",
        "tests/accounts/passwords/test_managed_reset_api.py::ManagedResetPasswordApiTests::",
        "tests/library/catalog/test_author_axes.py::LibraryAuthorAxisTests::test_librarian_manager_and_owner_can_create_author",
        "tests/library/groups/test_book_assignment_create.py::LibraryGroupBookAssignmentCreateTests::",
        "tests/library/groups/test_membership_delete.py::LibraryGroupMembershipDeleteTests::",
        "tests/library/groups/test_membership_list.py::LibraryGroupMembershipListTests::",
        "tests/marginalia/imports/test_apply_api.py::MarginaliaImportApplyConcurrencyTests::",
        "tests/shelves/api/test_permissions.py::ShelvesPermissionTests::",
        "tests/shelves/api/test_shelf_create.py::ShelfCreateEndpointTests::",
        "tests/shelves/api/test_shelf_detail.py::ShelfDetailEndpointTests::",
        "tests/shelves/api/test_shelf_list.py::ShelfListEndpointTests::",
    ),
}


def _path_matches(path: str, candidate: str) -> bool:
    return path.startswith(candidate) if candidate.endswith("/") else path == candidate


def markers_for_test(*, path: str, nodeid: str) -> Iterable[str]:
    """Return the audited lane markers for one collected test."""

    for marker_name, candidates in _PATH_MARKERS.items():
        if any(_path_matches(path, candidate) for candidate in candidates):
            yield marker_name
    for marker_name, prefixes in _NODE_MARKERS.items():
        if any(nodeid.startswith(prefix) for prefix in prefixes):
            yield marker_name
