"""Tests for Import Marginalia Product UI."""
from pathlib import Path

from django.contrib.auth import get_user_model
from tests.core.product_ui.helpers import ProductUiTestCase


User = get_user_model()

class ProductUiImportMarginaliaTests(ProductUiTestCase):
    """Test reading sessions, import/export pages."""

    def test_unauthenticated_reading_import_redirects_to_login(self):
        response = self.client.get("/reading/import/", follow=False)
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response["Location"], "/api-auth/login/?next=/reading/import/")

    def test_authenticated_reading_import_returns_200(self):
        self.client.force_login(self.user)
        response = self.client.get("/reading/import/")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'aria-label="Breadcrumb"')
        self.assertContains(
            response,
            '<a class="breadcrumbs__link" href="/reading/sessions/">My Marginalia</a>',
            html=False,
        )
        self.assertContains(response, 'aria-current="page">Import Marginalia</li>', html=False)
        self.assertContains(response, "Import Marginalia")
        self.assertContains(response, "Preview native SPL JSON and import only exact file-hash matches.")
        self.assertContains(response, "SPL native marginalia export")
        self.assertContains(response, "Server import requires a visible local book with the same file hash")
        self.assertContains(response, "EPUB CFI-shaped locators")
        self.assertContains(response, "Reader-assisted import through the SecondPass Reading Client")
        self.assertContains(response, 'id="reading-import-preview-form"')
        self.assertContains(response, 'id="reading-import-file"')
        self.assertContains(response, 'id="reading-import-apply-controls"')
        self.assertContains(response, 'id="reading-import-apply-results"')
        self.assertContains(response, 'id="reading-import-session-modal"')
        self.assertContains(response, 'id="reading-import-session-modal-name"')
        self.assertContains(response, 'id="reading-import-session-modal-notes"')
        self.assertContains(response, 'href="/reading/export/"')
        self.assertContains(response, "Export Marginalia")
        self.assertNotContains(response, "Browse by Session")
        self.assertNotContains(response, "Export center")
        self.assertNotContains(response, "Reading sessions")

    def test_reading_import_js_wires_apply_after_preview(self):
        js = Path("web/static/web/js/reading/import_preview.js").read_text()
        rendering_js = Path("web/static/web/js/reading/import_rendering.js").read_text()
        selection_js = Path("web/static/web/js/reading/import_selection.js").read_text()
        modal_js = Path("web/static/web/js/reading/import_edit_modal.js").read_text()
        self.assertIn("renderApplyControls", js)
        self.assertIn("Apply import", rendering_js)
        self.assertIn("Select all", rendering_js)
        self.assertIn("Select none", rendering_js)
        self.assertIn("Some marks need the Reader.", rendering_js)
        self.assertIn("Download unmatched marginalia", rendering_js)
        self.assertIn("Reader-assisted import", rendering_js)
        self.assertIn("not safe for server-side import", rendering_js)
        self.assertIn("exact book file-hash match", rendering_js)
        self.assertIn("valid EPUB CFI-shaped locators", rendering_js)
        self.assertIn("unmatched_entries", rendering_js)
        self.assertIn("unmatched_books", rendering_js)
        self.assertIn("unmatched_sessions", rendering_js)
        self.assertIn("Needs Reader", rendering_js)
        self.assertIn("unmatched_download_url", rendering_js)
        self.assertIn("reading-import-select-all-top", rendering_js)
        self.assertIn("import-book-select", rendering_js)
        self.assertIn("import-book-select--large", rendering_js)
        self.assertIn("import-session-select", rendering_js)
        self.assertIn("import-session-edit", rendering_js)
        self.assertIn("Matched to", rendering_js)
        self.assertIn("bookMetadataParts", rendering_js)
        self.assertIn("matchLine", rendering_js)
        self.assertIn("humanizeMatchMethod", rendering_js)
        self.assertIn("countText", rendering_js)
        self.assertIn("formatDate", rendering_js)
        self.assertIn("Possible duplicate sessions found.", rendering_js)
        self.assertIn("suppressedSessionWarning", rendering_js)
        self.assertIn("renderMetaList", rendering_js)
        self.assertIn('class="meta-item"', rendering_js)
        self.assertIn("Matched to ${title}", rendering_js)
        self.assertIn('renderMetaList(["Needs Reader", "No file-hash match"])', rendering_js)
        self.assertIn('replace(/_/g, " ")', rendering_js)
        self.assertNotIn("&middot;", rendering_js)
        self.assertNotIn("&#183;", rendering_js)
        self.assertNotIn("Match unmatched", rendering_js)
        self.assertNotIn('"Matched to", title', rendering_js)
        self.assertNotIn("Match: <span", rendering_js)
        self.assertNotIn("Method:", rendering_js)
        self.assertNotIn("annotation(s), ${escapeHtml(session.bookmark_count)}", rendering_js)
        self.assertIn("reading-import-session-modal", js)
        self.assertIn("bookBox.indeterminate", selection_js)
        self.assertIn("No matched local books can be imported.", rendering_js)
        self.assertIn("import-session-name", modal_js)
        self.assertIn("/api/v1/reading/import/apply/", js)
        self.assertIn('formData.append("import_token", currentImportToken)', js)
        self.assertIn('formData.append("selection"', js)
        self.assertIn("buildSelection", js)
        self.assertIn("clearImportData", js)
        self.assertIn('input.value = ""', js)
        self.assertIn("currentPreview = null", js)
        self.assertIn("target.disabled = true", js)
        self.assertIn("renderApplyResult", js)
        self.assertIn("sessions_created", rendering_js)
        self.assertIn("bookmarks_created", rendering_js)
        self.assertIn("commented_highlights_created", rendering_js)
