# Generated by Django 6.0.4 on 2026-05-13 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
