# Generated by Django 6.0.4 on 2026-05-17 23:21

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_idempotencyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='expires_at',
            field=models.DateTimeField(default=core.models._default_idempotency_expires_at),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
