# Generated by Django 6.0.8 on 2026-09-25 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress_location",
                    models.TextField(blank=True, default="", max_length=8192),
                ),
                (
                    "progress_location_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("progress_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marginalia_sessions",
                        to="library.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marginalia_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("bookmark", "Bookmark"), ("highlight", "Highlight")],
                        max_length=16,
                    ),
                ),
                ("location", models.TextField(max_length=8192)),
                (
                    "location_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "highlight_text",
                    models.TextField(blank=True, default="", max_length=65536),
                ),
                (
                    "comment_text",
                    models.TextField(blank=True, default="", max_length=65536),
                ),
                (
                    "quote_prefix",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "quote_suffix",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "highlight_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("pink", "Pink"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="marginalia.readingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("include_empty_sessions", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("applying", "Applying"),
                            ("applied", "Applied"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("storage_name", models.CharField(max_length=255, unique=True)),
                ("preview", models.JSONField()),
                (
                    "request_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marginalia_import_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["ready", "applying", "applied"])
                        ),
                        name="marginalia_import_stage_state_is_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("applied_at__isnull", True),
                                ("request_fingerprint", ""),
                                ("result__isnull", True),
                                ("state__in", ["ready", "applying"]),
                            ),
                            models.Q(
                                ("applied_at__isnull", False),
                                ("state", "applied"),
                                models.Q(("request_fingerprint", ""), _negated=True),
                                ("result__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="marginalia_import_stage_result_is_complete",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "closed"])),
                name="marginalia_session_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "book"),
                name="marginalia_one_active_session_per_user_book",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("closed_at__isnull", False), ("status", "closed")),
                    models.Q(("status", "closed"), _negated=True),
                    _connector="OR",
                ),
                name="marginalia_closed_session_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("closed_at__isnull", True), ("status", "active")),
                    models.Q(("status", "active"), _negated=True),
                    _connector="OR",
                ),
                name="marginalia_active_session_has_no_closed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("progress_location", ""),
                        ("progress_location_label", ""),
                        ("progress_updated_at__isnull", True),
                    ),
                    models.Q(
                        models.Q(("progress_location", ""), _negated=True),
                        ("progress_updated_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="marginalia_session_progress_is_complete",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["session", "is_deleted", "created_at"],
                name="marg_sess_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["is_deleted", "deleted_at"], name="marg_ann_del_at_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["bookmark", "highlight"])),
                name="marginalia_annotation_kind_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("client_id", ""), _negated=True),
                name="marginalia_annotation_has_client_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                fields=("session", "client_id"),
                name="marginalia_annotation_client_id_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("location", ""), _negated=True),
                name="marginalia_annotation_has_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "highlight"), _negated=True),
                    models.Q(("highlight_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="marginalia_highlight_has_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "bookmark"), _negated=True),
                    models.Q(
                        ("comment_text", ""),
                        ("highlight_color", ""),
                        ("highlight_text", ""),
                        ("quote_prefix", ""),
                        ("quote_suffix", ""),
                    ),
                    _connector="OR",
                ),
                name="marginalia_bookmark_has_no_content",
            ),
        ),
    ]
