# Generated by Django 6.0.7 on 2026-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marginalia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='marg_sess_del_updated_idx',
        ),
        migrations.AddField(
            model_name='annotation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='marg_ann_del_at_idx'),
        ),
    ]
