# Generated by Django 6.0.7 on 2026-08-16 00:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceTaskConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_key",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual only"),
                            ("hourly", "Hourly"),
                            ("6_hours", "Every 6 hours"),
                            ("12_hours", "Every 12 hours"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_dispatched_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Maintenance Task",
                "verbose_name_plural": "Maintenance Tasks",
                "ordering": ("task_key",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "frequency__in",
                                [
                                    "manual",
                                    "hourly",
                                    "6_hours",
                                    "12_hours",
                                    "daily",
                                    "weekly",
                                ],
                            )
                        ),
                        name="maintenance_frequency_is_bounded",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_key", models.CharField(editable=False, max_length=100)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("admin", "Admin Run now"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("result_summary", models.TextField(blank=True, editable=False)),
                (
                    "result_counts",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("failure_summary", models.TextField(blank=True, editable=False)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="maintenance.maintenancetaskconfig",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_maintenance_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Task Run",
                "verbose_name_plural": "Maintenance Task Runs",
                "ordering": ("-queued_at",),
                "indexes": [
                    models.Index(
                        fields=["task_key", "-queued_at"],
                        name="maintenance_task_ke_7921ad_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("queued", "running"))),
                        fields=("task_key",),
                        name="maintenance_one_active_run_per_task",
                    )
                ],
            },
        ),
    ]
