# Generated by Django 6.0.7 on 2026-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenancetaskconfig',
            name='maintenance_frequency_is_bounded',
        ),
        migrations.AlterField(
            model_name='maintenancetaskconfig',
            name='frequency',
            field=models.CharField(choices=[('manual', 'Manual only'), ('hourly', 'Hourly'), ('6_hours', 'Every 6 hours'), ('12_hours', 'Every 12 hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='maintenancetaskconfig',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__in', ['manual', 'hourly', '6_hours', '12_hours', 'daily', 'weekly', 'monthly'])), name='maintenance_frequency_is_bounded'),
        ),
    ]
