# Generated by Django 6.0.8 on 2026-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenancetaskconfig_maintenance_frequency_is_bounded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetaskrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='queued', editable=False, max_length=16),
        ),
    ]
