# Generated by Django 6.0.4 on 2026-05-05 01:48

from django.db import migrations, models


def migrate_userprofile_roles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(role="admin").update(role="manager")
    UserProfile.objects.filter(role="user").update(role="reader")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('librarian', 'Librarian'), ('reader', 'Reader')], default='reader', max_length=16),
        ),
        migrations.RunPython(migrate_userprofile_roles, migrations.RunPython.noop),
    ]
