# Generated by Django 6.0.4 on 2026-06-18 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientloginrequest_userclientsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('issuer', models.URLField(max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('email_at_login', models.EmailField(blank=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('selected_claims', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'issuer', 'subject'],
                'indexes': [models.Index(fields=['provider', 'subject'], name='acct_ext_provider_subj_idx')],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='unique_external_identity_issuer_subject')],
            },
        ),
    ]
