export {
  changeCurrentUserPassword,
  canSeeImports,
  canSeeServerSettings,
  canSeeUsers,
  getCurrentUser,
  isAtLeastLibrarian,
  isAtLeastManager,
  updateCurrentUser,
  type ChangeCurrentUserPasswordInput,
  type CurrentUser,
  type CurrentUserRoleFacts,
  type UpdateCurrentUserInput,
} from "./accounts";
export {
  listClientSessions,
  logoutOtherWebSessions,
  revokeClientSession,
  type ClientSession,
} from "./accountSessions";
export {
  decideClientPairing,
  lookupClientPairing,
  type ClientPairingRequest,
} from "./pairing";
export {
  ApiError,
  classifyApiError,
  isAuthenticationError,
  type ApiErrorDetails,
  type ApiErrorKind,
} from "./errors";
export { toPage, type ApiPage, type Page } from "./pagination";
export {
  addBookToGroup,
  listAllLibraryGroups,
  listGroups,
  removeBookFromGroup,
  type BookGroupAssignment,
  type LibraryGroup,
  type LibraryGroupsQuery,
} from "./groups";
export {
  listAllShelvesForBook,
  listShelves,
  type ShelfOrdering,
  type ShelfOwnerGroup,
  type ShelfOwnerType,
  type ShelfOwnerUser,
  type ShelfSummary,
  type ShelvesQuery,
  type ShelfVisibility,
} from "./shelves";
export {
  getBook,
  clearBookCover,
  replaceBookCover,
  getAuthor,
  getSeries,
  createAuthor,
  createSeries,
  updateAuthor,
  updateSeries,
  updateBook,
  bookIdentifierSchemes,
  listAllCatalogTags,
  listAllAuthors,
  listAllSeries,
  listAuthors,
  listBooks,
  listCatalogTags,
  listSeries,
  type BookAuthorSummary,
  type AuthorMutationInput,
  type BookDetail,
  type BookFileDetail,
  type BookGroupSummary,
  type BookIdentifier,
  type BookIdentifierInput,
  type BookIdentifierScheme,
  type BookOrdering,
  type BookPreview,
  type BookSeriesSummary,
  type CatalogTag,
  type CatalogTagSummary,
  type CompactBook,
  type LibraryAuthor,
  type LibraryAxisOrdering,
  type LibraryAxisQuery,
  type LibraryBooksQuery,
  type LibrarySeries,
  type SeriesMutationInput,
  type UpdateBookInput,
} from "./library";
export {
  uploadLibraryImport,
  type ImportItemStatus,
  type LibraryImportCounts,
  type LibraryImportItem,
  type LibraryImportResult,
} from "./imports";
export { getServerInfo, type ServerInfo } from "./server";
export {
  enableAdvancedGroups,
  getServerSettings,
  updateGeneralSettings,
  updatePublicLibrarySettings,
  type GeneralServerSettings,
  type LibraryGroupsSettings,
  type PublicLibrarySettings,
  type ServerSettings,
  type UpdateGeneralSettingsInput,
  type UpdatePublicLibrarySettingsInput,
} from "./serverSettings";
export {
  addUserGroupMembership,
  createUser,
  getManagedUser,
  listAssignableGroupsForUser,
  listUsers,
  removeUserGroupMembership,
  resetManagedUserPassword,
  updateManagedUser,
  updateUserGroupCurator,
  type AddUserGroupMembershipInput,
  type AssignableGroup,
  type CreateUserInput,
  type CreateUserResult,
  type CreateUserRole,
  type ManagedPasswordResetResult,
  type ManagedUser,
  type ManagedUserGroup,
  type ManagedUserRole,
  type UpdateManagedUserInput,
  type UserOrdering,
  type UserRoleFilter,
  type UsersListQuery,
  type UserStatusFilter,
} from "./users";
