export {
  changeCurrentUserPassword,
  canSeeImports,
  canSeeServerSettings,
  canSeeUsers,
  getCurrentUser,
  isAtLeastLibrarian,
  isAtLeastManager,
  updateCurrentUser,
  type ChangeCurrentUserPasswordInput,
  type CurrentUser,
  type CurrentUserRoleFacts,
  type UpdateCurrentUserInput,
} from "./accounts";
export {
  listClientSessions,
  logoutOtherWebSessions,
  revokeClientSession,
  type ClientSession,
} from "./accountSessions";
export {
  decideClientPairing,
  lookupClientPairing,
  type ClientPairingRequest,
} from "./pairing";
export {
  ApiError,
  classifyApiError,
  isAuthenticationError,
  type ApiErrorDetails,
  type ApiErrorKind,
} from "./errors";
export { toPage, type ApiPage, type Page } from "./pagination";
export {
  addGroupMember,
  addBookToGroup,
  createGroup,
  deleteGroup,
  getGroup,
  listAllGroupsForBook,
  listAllLibraryGroups,
  listGroupBooks,
  listGroupMembers,
  listGroups,
  removeBookFromGroup,
  removeGroupMember,
  updateGroupMember,
  updateGroup,
  type BookGroupAssignment,
  type AddGroupMemberInput,
  type CreateGroupInput,
  type GroupBooksQuery,
  type GroupMembersQuery,
  type GroupMembership,
  type LibraryGroup,
  type LibraryGroupsQuery,
  type UpdateGroupInput,
  type UpdateGroupMemberInput,
} from "./groups";
export {
  addShelfItem,
  createShelf,
  deleteShelf,
  getShelf,
  listAllGroupShelvesForBook,
  listAllShelvesForBook,
  listShelfItems,
  listShelfEditorItems,
  listShelves,
  moveShelfItem,
  removeShelfItem,
  updateShelf,
  type AddShelfItemInput,
  type CreateShelfInput,
  type ShelfItem,
  type ShelfEditorItem,
  type ShelfEditorItemsPage,
  type ShelfEditorItemsQuery,
  type ShelfItemOrdering,
  type ShelfItemsQuery,
  type ShelfOrdering,
  type ShelfOwnerGroup,
  type ShelfOwnerType,
  type ShelfOwnerUser,
  type ShelfSummary,
  type ShelfScope,
  type ShelvesQuery,
  type ShelfVisibility,
  type UpdateShelfInput,
} from "./shelves";
export {
  getBook,
  clearBookCover,
  replaceBookCover,
  getAuthor,
  getSeries,
  createAuthor,
  createSeries,
  updateAuthor,
  updateSeries,
  updateBook,
  bookIdentifierSchemes,
  listAllCatalogTags,
  listAllAuthors,
  listAllSeries,
  listAuthors,
  listBooks,
  searchLibraryBooks,
  listCatalogTags,
  listSeries,
  type BookAuthorSummary,
  type AuthorMutationInput,
  type BookDetail,
  type BookFileDetail,
  type BookGroupSummary,
  type BookIdentifier,
  type BookIdentifierInput,
  type BookIdentifierScheme,
  type BookOrdering,
  type BookPreview,
  type BookSeriesSummary,
  type CatalogTag,
  type CatalogTagSummary,
  type CompactBook,
  type LibraryAuthor,
  type LibraryAxisOrdering,
  type LibraryAxisQuery,
  type LibraryBookSearchQuery,
  type LibraryBooksQuery,
  type LibrarySeries,
  type SeriesMutationInput,
  type UpdateBookInput,
} from "./library";
export {
  uploadLibraryImport,
  type ImportItemStatus,
  type LibraryImportCounts,
  type LibraryImportItem,
  type LibraryImportResult,
} from "./imports";
export {
  getServerDiscovery,
  getServerInfo,
  type ServerDiscovery,
  type ServerInfo,
} from "./server";
export {
  enableAdvancedGroups,
  getServerSettings,
  updateGeneralSettings,
  updatePublicLibrarySettings,
  type GeneralServerSettings,
  type LibraryGroupsSettings,
  type PublicLibrarySettings,
  type ServerSettings,
  type UpdateGeneralSettingsInput,
  type UpdatePublicLibrarySettingsInput,
} from "./serverSettings";
export {
  createUser,
  getManagedUser,
  listAssignableGroupsForUser,
  listUserChoices,
  listUsers,
  resetManagedUserPassword,
  updateManagedUser,
  type AssignableGroup,
  type CreateUserInput,
  type CreateUserResult,
  type CreateUserRole,
  type ManagedPasswordResetResult,
  type ManagedUser,
  type ManagedUserGroup,
  type ManagedUserRole,
  type UpdateManagedUserInput,
  type UserOrdering,
  type UserChoice,
  type UserChoicesQuery,
  type UserRoleFilter,
  type UsersListQuery,
  type UserStatusFilter,
} from "./users";
