# Generated by Django 6.0.4 on 2026-05-22 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0003_alter_bookfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.JSONField(default=dict)),
                ('progression', models.FloatField(blank=True, null=True)),
                ('profile_version', models.CharField(default='0.1.0', max_length=16)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='reading.readingsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivation', models.CharField(blank=True, choices=[('highlighting', 'Highlighting'), ('commenting', 'Commenting'), ('bookmarking', 'Bookmarking')], max_length=32, null=True)),
                ('selector_kind', models.CharField(default='epub_cfi', max_length=32)),
                ('selector_value', models.TextField()),
                ('highlight_text', models.TextField(blank=True, default='')),
                ('highlight_color', models.CharField(blank=True, default='', max_length=32)),
                ('comment_text', models.TextField(blank=True, default='')),
                ('source_import', models.JSONField(blank=True, default=dict)),
                ('profile_version', models.CharField(default='0.1.0', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='library.book')),
                ('book_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='library.bookfile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='reading.readingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'book'), name='unique_active_reading_session_per_user_book'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['session', 'is_deleted', 'created_at'], name='reading_ann_session_1e7f17_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['session', 'is_deleted', 'updated_at'], name='reading_ann_session_fed308_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['book', 'is_deleted', 'created_at'], name='reading_ann_book_id_5311b3_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['book', 'is_deleted', 'updated_at'], name='reading_ann_book_id_32f710_idx'),
        ),
    ]
