# Generated by Django 6.0.4 on 2026-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='quote_prefix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annotation',
            name='quote_suffix',
            field=models.TextField(blank=True, default=''),
        ),
    ]
