# Generated by Django 6.0.4 on 2026-05-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='device',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
