# Generated by Django 6.0.4 on 2026-05-31 21:55

from django.db import migrations, models
from django.db.models import Q


def populate_anchor_kind(apps, schema_editor):
    Annotation = apps.get_model("reading", "Annotation")

    # Bookmarks.
    Annotation.objects.filter(motivation="bookmarking").update(anchor_kind="bookmark")

    # Highlights.
    Annotation.objects.filter(motivation="highlighting").update(anchor_kind="highlight")

    # Legacy comment-only rows:
    # - If highlight_text exists, treat as a highlight-with-note.
    # - If highlight_text is missing but comment_text exists, treat as a highlight by
    #   copying comment_text into highlight_text (unreleased system; prefer preserving
    #   user data over forced data loss).
    Annotation.objects.filter(motivation="commenting", highlight_text__gt="").update(
        anchor_kind="highlight"
    )
    Annotation.objects.filter(motivation="commenting").filter(
        Q(highlight_text="") | Q(highlight_text__isnull=True)
    ).filter(comment_text__gt="").update(
        anchor_kind="highlight",
        highlight_text=models.F("comment_text"),
        highlight_color="yellow",
    )

    # If both highlight_text and comment_text are blank, leave as bookmark (rare/invalid).
    Annotation.objects.filter(motivation="commenting").filter(
        Q(highlight_text="") | Q(highlight_text__isnull=True)
    ).filter(Q(comment_text="") | Q(comment_text__isnull=True)).update(anchor_kind="bookmark")


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_annotation_quote_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='anchor_kind',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('highlight', 'Highlight')], default='bookmark', max_length=16),
        ),
        migrations.RunPython(populate_anchor_kind, migrations.RunPython.noop),
    ]
