# Generated by Django 6.0.4 on 2026-05-11 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_remove_readingsession_unique_active_reading_session_per_user_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='locator',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='selected_text',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='locator',
        ),
        migrations.AddField(
            model_name='annotation',
            name='body',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='annotation',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_annotations', to='reading.annotation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='motivation',
            field=models.CharField(blank=True, choices=[('highlighting', 'Highlighting'), ('commenting', 'Commenting'), ('bookmarking', 'Bookmarking')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='source_import',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='annotation',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_annotations', to='reading.readingsession'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='current_location',
            field=models.JSONField(default=dict),
        ),
    ]
