# Generated by Django 6.0.4 on 2026-06-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_annotation_anchor_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='source_import',
        ),
    ]
