# Generated by Django 6.0.4 on 2026-05-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_remove_annotation_color_remove_annotation_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='source_session',
        ),
    ]
