# Generated by Django 6.0.4 on 2026-05-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_remove_annotation_derived_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='profile_version',
            field=models.CharField(default='0.1.0', max_length=16),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='profile_version',
            field=models.CharField(default='0.1.0', max_length=16),
        ),
    ]
