"""
Django settings for secondpass project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()


def _env_list(name: str, default: list[str]) -> list[str]:
    # Normalize comma-separated env lists so spaces and trailing commas do not
    # become accidental host/origin/check values.
    return [item.strip() for item in env.list(name, default=default) if item.strip()]


def _staticfiles_backend(*, debug: bool) -> str:
    if debug:
        return "django.contrib.staticfiles.storage.StaticFilesStorage"
    return "whitenoise.storage.CompressedManifestStaticFilesStorage"


def _secure_proxy_ssl_header() -> tuple[str, str] | None:
    if env.bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=False):
        return ("HTTP_X_FORWARDED_PROTO", "https")
    return None


INSECURE_FALLBACK_SECRET_KEY = (
    "django-insecure-t&^j-sap##2x=r@ws#*0nbmd!@!bv=u852pz&&7a9sd0_!3^#$"
)
PLACEHOLDER_SECRET_KEYS = {
    "replace-me-with-a-generated-secret",
}


def _secret_key(*, debug: bool) -> str:
    value = env.str("DJANGO_SECRET_KEY", default=None)
    if debug:
        return value or INSECURE_FALLBACK_SECRET_KEY
    if (
        not value
        or value == INSECURE_FALLBACK_SECRET_KEY
        or value in PLACEHOLDER_SECRET_KEYS
    ):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set to a non-default value when DEBUG=False."
        )
    return value


# User data directory for runtime data
USERDATA_DIR = Path(env.path("SECOND_PASS_USERDATA_DIR", default=str(BASE_DIR / "userdata")))
RUNNING_TESTS = "test" in sys.argv

SECOND_PASS_SERVER_VERSION = env.str("SECOND_PASS_SERVER_VERSION", default="0.1.0-dev")
SECOND_PASS_SERVER_RELEASE = env.str("SECOND_PASS_SERVER_RELEASE", default="pre-release")
SECOND_PASS_SERVER_RELEASE_DATE = env.str(
    "SECOND_PASS_SERVER_RELEASE_DATE", default="2026-07-03"
)

# Ensure required directories exist
(USERDATA_DIR / "db").mkdir(parents=True, exist_ok=True)
(USERDATA_DIR / "media").mkdir(parents=True, exist_ok=True)
(USERDATA_DIR / "imports").mkdir(parents=True, exist_ok=True)
IMPORTS_DIR = USERDATA_DIR / "imports"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)
SILENCED_SYSTEM_CHECKS = _env_list("DJANGO_SILENCED_SYSTEM_CHECKS", [])
SECOND_PASS_ENABLE_DJANGO_ADMIN = env.bool(
    "SECOND_PASS_ENABLE_DJANGO_ADMIN", default=False
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _secret_key(debug=DEBUG or RUNNING_TESTS)

LOCAL_ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", LOCAL_ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])

SECURE_PROXY_SSL_HEADER = _secure_proxy_ssl_header()
USE_X_FORWARDED_HOST = env.bool("DJANGO_USE_X_FORWARDED_HOST", default=False)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "web",
    "core.apps.CoreConfig",
    "accounts",
    "library.apps.LibraryConfig",
    "reading",
    "shelves",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.UserWebSessionMiddleware",
    "web.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "secondpass.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.server_identity",
            ],
        },
    },
]

WSGI_APPLICATION = "secondpass.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": USERDATA_DIR / "db" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env.str("DJANGO_TIME_ZONE", default="America/Phoenix")

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# MEDIA_URL is the canonical URL prefix for public cover assets.
# Only MEDIA_ROOT/covers is exposed through /media/covers/ by secondpass/urls.py.
# Stored EPUB files under MEDIA_ROOT/books are not public raw media and must be
# delivered through authenticated app/API views.
MEDIA_URL = "/media/"
MEDIA_ROOT = USERDATA_DIR / "media"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPageNumberPagination",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "null": {
            "class": "logging.NullHandler",
        },
    },
    "loggers": {
        "library.imports.upload": {
            "handlers": ["null"] if RUNNING_TESTS else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "library.management.commands.import_epub": {
            "handlers": ["null"] if RUNNING_TESTS else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "library.management.commands.import_books": {
            "handlers": ["null"] if RUNNING_TESTS else ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "var" / "static"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _staticfiles_backend(debug=DEBUG or RUNNING_TESTS),
    },
}
WHITENOISE_MANIFEST_STRICT = False

# Browser/session security.
_SECURE_COOKIES = env.bool("DJANGO_SECURE_COOKIES", default=False)
SESSION_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_SECURE = _SECURE_COOKIES
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
# Product UI JavaScript reads the CSRF cookie to send X-CSRFToken.
CSRF_COOKIE_HTTPONLY = False

# Product UI pages reuse DRF's built-in login views.
LOGIN_URL = "/api-auth/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# CORS
#
# Default policy: open CORS for API + discovery endpoints only.
# This supports standalone reader clients from arbitrary browser origins.
# Cross-origin cookie/session credentials remain disabled; bearer tokens are the
# security boundary for protected API data.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False
CORS_URLS_REGEX = r"^/api/|^/\.well-known/"
# Allow Idempotency-Key for safe retries from browser clients.
CORS_ALLOW_HEADERS = list(default_headers) + ["idempotency-key"]
