"""Tests for Product UI navigation and breadcrumb source contracts."""
from pathlib import Path

from tests.core.product_ui.helpers import ProductUiTestCase

class ProductUiNavigationContractsTests(ProductUiTestCase):
    """Test shared UI contracts and component helpers."""

    def test_product_ui_tabs_use_shared_helper(self):
        helper_js = Path("web/static/web/js/ui/tabs.js").read_text(encoding="utf-8")
        book_edit_main_js = Path("web/static/web/js/book_edit/main.js").read_text(encoding="utf-8")
        group_shared_js = Path("web/static/web/js/groups/shared.js").read_text(encoding="utf-8")
        group_edit_js = Path("web/static/web/js/groups/edit.js").read_text(encoding="utf-8")
        group_view_js = Path("web/static/web/js/groups/view.js").read_text(encoding="utf-8")
        group_navigation_js = Path("web/static/web/js/groups/navigation.js").read_text(encoding="utf-8")
        shelf_edit_js = Path("web/static/web/js/shelves/edit.js").read_text(encoding="utf-8")
        shelf_view_js = Path("web/static/web/js/shelves/view.js").read_text(encoding="utf-8")
        shelf_navigation_js = Path("web/static/web/js/shelves/navigation.js").read_text(encoding="utf-8")
        book_detail_js = Path("web/static/web/js/library/detail.js").read_text(encoding="utf-8")
        user_edit_js = Path("web/static/web/js/users/edit.js").read_text(encoding="utf-8")
        users_list_js = Path("web/static/web/js/users/list.js").read_text(encoding="utf-8")
        user_navigation_js = Path("web/static/web/js/users/navigation.js").read_text(encoding="utf-8")

        self.assertIn("export function initTabs", helper_js)
        self.assertIn(".tab-button[data-tab]", helper_js)
        self.assertIn("[data-tab-panel]", helper_js)
        self.assertIn("aria-selected", helper_js)
        self.assertIn("aria-hidden", helper_js)
        self.assertIn("is-active", helper_js)
        self.assertIn("is-hidden", helper_js)

        self.assertIn('from "../ui/tabs.js"', book_edit_main_js)
        self.assertIn('from "../ui/breadcrumbs.js"', book_edit_main_js)
        self.assertIn('defaultTab: "book-details"', book_edit_main_js)
        self.assertNotIn('from "./tabs.js"', book_edit_main_js)
        self.assertIn("function syncBookEditBreadcrumbs", book_edit_main_js)
        self.assertIn('{ label: "Library", href: "/library/" }', book_edit_main_js)
        self.assertIn('{ label: "Books", href: "/library/?view=books" }', book_edit_main_js)
        self.assertIn('href: `/library/books/${encodeURIComponent(String(bookId))}/`', book_edit_main_js)
        self.assertIn('{ label: "Edit", current: true }', book_edit_main_js)
        self.assertIn("bookDisplayTitle(state.book)", book_edit_main_js)
        self.assertNotIn("history.back", book_edit_main_js)
        self.assertNotIn("initTabs", group_shared_js)
        self.assertNotIn('from "../ui/tabs.js"', group_edit_js)
        self.assertIn('from "./navigation.js"', group_edit_js)
        self.assertIn("initGroupEditNavigation(root, groupId)", group_edit_js)
        self.assertIn("syncGroupEditBreadcrumb({ groupId, groupName: \"Group\" })", group_edit_js)
        self.assertIn("syncGroupEditBreadcrumb({ groupId, groupName: group.name || \"Group\" })", group_edit_js)
        self.assertIn('from "../ui/tabs.js"', group_view_js)
        self.assertIn('from "./navigation.js"', group_view_js)
        self.assertIn("groupViewTabFromSearch", group_view_js)
        self.assertIn("selectGroupViewTab(root, initialTab)", group_view_js)
        self.assertIn("setGroupViewUrl(groupId", group_view_js)
        self.assertIn("window.addEventListener(\"popstate\"", group_view_js)
        self.assertIn("syncGroupBreadcrumb({ groupName: \"Group\" })", group_view_js)
        self.assertIn("syncGroupBreadcrumb({ groupName: group.name || \"Group\" })", group_view_js)
        self.assertIn("export function groupViewTabFromSearch", group_navigation_js)
        self.assertIn("export function groupEditTabFromSearch", group_navigation_js)
        self.assertIn("export function groupViewHref", group_navigation_js)
        self.assertIn("export function groupEditHref", group_navigation_js)
        self.assertIn("export function setGroupViewUrl", group_navigation_js)
        self.assertIn("export function setGroupEditUrl", group_navigation_js)
        self.assertIn("export function selectGroupViewTab", group_navigation_js)
        self.assertIn("export function selectGroupEditTab", group_navigation_js)
        self.assertIn("export function initGroupEditNavigation", group_navigation_js)
        self.assertIn("export function syncGroupBreadcrumb", group_navigation_js)
        self.assertIn("export function syncGroupEditBreadcrumb", group_navigation_js)
        self.assertIn('const GROUP_VIEW_TABS = new Set(["books", "members", "shelves"])', group_navigation_js)
        self.assertIn('const GROUP_EDIT_TABS = new Set(["details", "books", "members", "shelves"])', group_navigation_js)
        self.assertIn('return tab && tab !== "books" ? `${base}?view=${encodeURIComponent(String(tab))}` : base', group_navigation_js)
        self.assertIn('return tab && tab !== "details" ? `${base}?view=${encodeURIComponent(String(tab))}` : base', group_navigation_js)
        self.assertIn('const base = `/groups/${encodeURIComponent(String(groupId))}/edit/`', group_navigation_js)
        self.assertIn('const view = (params.get("view") || "details").trim().toLowerCase()', group_navigation_js)
        self.assertIn('return GROUP_EDIT_TABS.has(view) ? view : "details"', group_navigation_js)
        self.assertIn("selectGroupEditTab(root, initialTab)", group_navigation_js)
        self.assertIn("setGroupEditUrl(groupId", group_navigation_js)
        self.assertIn('window.addEventListener("popstate"', group_navigation_js)
        self.assertIn('window.history.pushState', group_navigation_js)
        self.assertIn('window.history.replaceState', group_navigation_js)
        self.assertNotIn("history.back", group_navigation_js)
        self.assertIn('{ label: "Groups", href: "/groups/" }', group_navigation_js)
        self.assertIn('from "./navigation.js"', shelf_edit_js)
        self.assertIn('from "./navigation.js"', shelf_view_js)
        self.assertIn("initShelfEditNavigation(document, shelfId)", shelf_edit_js)
        self.assertIn("syncShelfEditBreadcrumb({ shelfId, shelfName: \"Shelf\" })", shelf_edit_js)
        self.assertIn("syncShelfEditBreadcrumb({ shelfId, shelfName: shelf.name || \"Shelf\" })", shelf_edit_js)
        self.assertIn("syncShelfBreadcrumb({ shelfName: \"Shelf\" })", shelf_view_js)
        self.assertIn("syncShelfBreadcrumb({ shelfName: shelf.name || \"Shelf\" })", shelf_view_js)
        self.assertIn("export function shelfEditTabFromSearch", shelf_navigation_js)
        self.assertIn("export function shelfEditHref", shelf_navigation_js)
        self.assertIn("export function setShelfEditUrl", shelf_navigation_js)
        self.assertIn("export function selectShelfEditTab", shelf_navigation_js)
        self.assertIn("export function initShelfEditNavigation", shelf_navigation_js)
        self.assertIn("export function syncShelfBreadcrumb", shelf_navigation_js)
        self.assertIn("export function syncShelfEditBreadcrumb", shelf_navigation_js)
        self.assertIn('const SHELF_EDIT_TABS = new Set(["books", "add", "details"])', shelf_navigation_js)
        self.assertIn('return tab && tab !== "books" ? `${base}?view=${encodeURIComponent(String(tab))}` : base', shelf_navigation_js)
        self.assertIn('const base = `/shelves/${encodeURIComponent(String(shelfId))}/edit/`', shelf_navigation_js)
        self.assertIn('const view = (params.get("view") || "books").trim().toLowerCase()', shelf_navigation_js)
        self.assertIn('return SHELF_EDIT_TABS.has(view) ? view : "books"', shelf_navigation_js)
        self.assertIn("selectShelfEditTab(root, initialTab)", shelf_navigation_js)
        self.assertIn("setShelfEditUrl(shelfId", shelf_navigation_js)
        self.assertIn('window.addEventListener("popstate"', shelf_navigation_js)
        self.assertIn('window.history.pushState', shelf_navigation_js)
        self.assertIn('window.history.replaceState', shelf_navigation_js)
        self.assertNotIn("history.back", shelf_navigation_js)
        self.assertIn('{ label: "Shelves", href: "/shelves/" }', shelf_navigation_js)
        self.assertIn('from "../ui/tabs.js"', book_detail_js)
        self.assertIn('from "../ui/breadcrumbs.js"', book_detail_js)
        self.assertIn('from "./navigation.js"', book_detail_js)
        self.assertNotIn("function initTabs(root)", book_detail_js)
        self.assertIn("function syncBookBreadcrumbs", book_detail_js)
        self.assertIn("bookDetailContextFromSearch(window.location.search)", book_detail_js)
        self.assertIn("async function loadBreadcrumbContext", book_detail_js)
        self.assertIn('const endpoint = context.kind === "author" ? "authors" : "series"', book_detail_js)
        self.assertIn("libraryContextHref(context)", book_detail_js)
        self.assertIn('{ label: "Library", href: "/library/" }', book_detail_js)
        self.assertIn('{ label: "Books", href: "/library/?view=books" }', book_detail_js)
        self.assertIn('{ label: "Authors", href: "/library/?view=authors" }', book_detail_js)
        self.assertIn('{ label: "Series", href: "/library/?view=series" }', book_detail_js)
        self.assertIn('{ label: context.name || "Author", href: libraryContextHref(context) }', book_detail_js)
        self.assertIn('{ label: context.name || "Series", href: libraryContextHref(context) }', book_detail_js)
        self.assertIn('{ label: title || "Book", current: true }', book_detail_js)
        self.assertIn("bookDisplayTitle(book)", book_detail_js)
        self.assertNotIn("author_name", book_detail_js)
        self.assertNotIn("series_name", book_detail_js)
        self.assertNotIn('from === "author"', book_detail_js)
        self.assertNotIn('from === "series"', book_detail_js)
        self.assertNotIn("history.back", book_detail_js)
        self.assertIn('from "./navigation.js"', user_edit_js)
        self.assertIn('from "./navigation.js"', users_list_js)
        self.assertIn("function applyUserPayload(payload)", user_edit_js)
        self.assertIn("syncUserEditBreadcrumb(null)", user_edit_js)
        self.assertIn("syncUserEditBreadcrumb(payload)", user_edit_js)
        self.assertIn("usersFilterFromSearch()", users_list_js)
        self.assertIn("setUsersFilterUrl(activeFilter)", users_list_js)
        self.assertIn("setActiveFilter(filter, { writeUrl: true })", users_list_js)
        self.assertIn('window.addEventListener("popstate"', users_list_js)
        self.assertNotIn("history.back", user_edit_js)
        self.assertNotIn("history.back", users_list_js)
        self.assertIn("export function usersFilterFromSearch", user_navigation_js)
        self.assertIn("export function usersFilterHref", user_navigation_js)
        self.assertIn("export function setUsersFilterUrl", user_navigation_js)
        self.assertIn('const USER_ROLE_FILTERS = new Set(["reader", "curator", "librarian", "manager"])', user_navigation_js)
        self.assertIn('if (role && status) return "all"', user_navigation_js)
        self.assertIn('return status === "inactive" ? "inactive" : "all"', user_navigation_js)
        self.assertIn('return USER_ROLE_FILTERS.has(role) ? role : "all"', user_navigation_js)
        self.assertIn('if (USER_ROLE_FILTERS.has(filter)) search.set("role", filter)', user_navigation_js)
        self.assertIn('if (filter === "inactive") search.set("status", "inactive")', user_navigation_js)
        self.assertIn('return query ? `/users/?${query}` : "/users/"', user_navigation_js)
        self.assertIn('window.history.pushState', user_navigation_js)
        self.assertIn('window.history.replaceState', user_navigation_js)
        self.assertIn('from "../ui/breadcrumbs.js"', user_navigation_js)
        self.assertIn("export function userBreadcrumbLabel(user)", user_navigation_js)
        self.assertIn("userDisplayName(user)", user_navigation_js)
        self.assertIn("if (user.username)", user_navigation_js)
        self.assertIn("if (user.email)", user_navigation_js)
        self.assertIn("export function syncUserEditBreadcrumb(user)", user_navigation_js)
        self.assertIn('{ label: "Users", href: "/users/" }', user_navigation_js)
        self.assertIn("{ label: userBreadcrumbLabel(user) }", user_navigation_js)
        self.assertIn('{ label: "Edit", current: true }', user_navigation_js)
        self.assertNotIn("history.back", user_navigation_js)

    def test_shelves_product_ui_list_uses_visibility_scoped_api(self):
        template = Path("web/templates/web/shelves/shelves.html").read_text(encoding="utf-8")
        list_js = Path("web/static/web/js/shelves/list.js").read_text()

        self.assertIn('id="shelves-results"', template)
        for scope in ("personal", "shared", "group"):
            self.assertIn(f'data-shelf-scope="{scope}"', template)
        self.assertIn('include_preview_books: "true"', list_js)
        self.assertIn("createPagedListController", list_js)
        self.assertIn('window.addEventListener("popstate"', list_js)
        self.assertIn("window.history.pushState", list_js)
        self.assertIn("window.history.replaceState", list_js)
        self.assertIn("shelfMetadataLine", list_js)
        self.assertIn("renderCoverPreviewStrip(shelf.preview_books", list_js)
        self.assertNotIn(".filter(", list_js)
        self.assertNotIn("owner_user.profile_id", list_js)
        self.assertNotIn(".email", list_js)
        self.assertNotIn("owner_user__is_staff", list_js)
        self.assertNotIn("is_superuser", list_js)
