from pathlib import Path

import pytest

from tests.core.product_ui.helpers import ProductUiTestCase


pytestmark = [pytest.mark.product_ui, pytest.mark.static_contract]


class ProductUiIdentityLibraryShelvesJsContractsTests(ProductUiTestCase):
    def test_shelf_js_has_friendly_ownership_display(self):
        shared_js = Path("web/static/web/js/shelves/shared.js").read_text(encoding="utf-8")
        library_list_js = Path("web/static/web/js/library/list.js").read_text(encoding="utf-8")
        library_prose_js = Path("web/static/web/js/library/prose.js").read_text(
            encoding="utf-8"
        )
        library_navigation_js = Path("web/static/web/js/library/navigation.js").read_text(
            encoding="utf-8"
        )
        users_list_js = Path("web/static/web/js/users/list.js").read_text(
            encoding="utf-8"
        )
        list_js = Path("web/static/web/js/shelves/list.js").read_text(encoding="utf-8")
        view_js = Path("web/static/web/js/shelves/view.js").read_text(encoding="utf-8")
        edit_js = Path("web/static/web/js/shelves/edit.js").read_text(encoding="utf-8")
        book_edit_shelves_js = Path("web/static/web/js/book_edit/shelves.js").read_text(encoding="utf-8")
        groups_shared_js = Path("web/static/web/js/groups/shared.js").read_text(encoding="utf-8")

        self.assertIn('from "../ui/groups.js"', shared_js)
        self.assertIn('from "../ui/identity.js"', shared_js)
        self.assertIn('if (shelf && shelf.owner_type === "group") return ""', shared_js)
        self.assertIn('label.textContent = "Shared by"', shared_js)
        self.assertIn('String(shelf.visibility || "") !== "listed"', shared_js)
        self.assertIn("ownerGroup && ownerGroup.is_public_group", shared_js)
        self.assertIn("!isPublicGroup && !advancedLibraryGroupsEnabled()", shared_js)
        self.assertIn("renderUserIdentity(shelf.owner_user", shared_js)
        self.assertIn("userIdentityText(shelf.created_by)", shared_js)
        self.assertNotIn("owner_user.first_name", shared_js)
        self.assertNotIn("owner_user.last_name", shared_js)
        self.assertNotIn("created_by.first_name", shared_js)
        self.assertNotIn("created_by.last_name", shared_js)
        self.assertIn("renderGroupBadge(shelf.owner_group", shared_js)
        self.assertIn("shelfOwnerIdentitySegment", shared_js)
        self.assertIn("shelfMetadataLine", shared_js)
        self.assertIn("renderShelfMetadata", shared_js)
        self.assertIn("groups", shared_js)
        self.assertIn("shelf-metadata-piece", shared_js)
        self.assertIn("profile_id", shared_js)
        self.assertNotIn("Owned by you", shared_js)
        self.assertNotIn("Owned by ", shared_js)
        self.assertNotIn("profile_id}</span>", shared_js)
        self.assertNotIn(".email", shared_js)
        self.assertNotIn("shelfOwnerChip", shared_js)

        self.assertIn('from "../ui/identity.js"', users_list_js)
        self.assertIn("renderUserIdentity(user", users_list_js)
        self.assertIn("userIdentityText", users_list_js)
        self.assertIn("includeEmail: true", users_list_js)
        self.assertIn("group.is_curator === true", users_list_js)
        self.assertNotIn("membership_role", users_list_js)
        self.assertNotIn('<span class="pill">active</span>', users_list_js)
        self.assertIn('<span class="pill">inactive</span>', users_list_js)
        self.assertIn("function titleCaseRole", users_list_js)
        self.assertIn("function userSortName", users_list_js)
        self.assertIn("function roleSortValue", users_list_js)
        self.assertIn("function lastLoginTime", users_list_js)
        self.assertIn("function renderHeader", users_list_js)
        self.assertIn("function sortButton", users_list_js)
        self.assertIn("function sortedUsers", users_list_js)
        self.assertIn('name: "Name"', users_list_js)
        self.assertIn('username: "Username"', users_list_js)
        self.assertIn('email: "Email"', users_list_js)
        self.assertIn('role: "Role"', users_list_js)
        self.assertIn('last_login: "Last Login"', users_list_js)
        self.assertIn('let sortKey = "role"', users_list_js)
        self.assertIn('let sortDirection = "desc"', users_list_js)
        self.assertIn('data-sort="${escapeHtml(key)}"', users_list_js)
        self.assertIn("aria-sort", users_list_js)
        self.assertIn("sortDirection", users_list_js)
        self.assertIn('source.closest("button[data-sort]")', users_list_js)
        self.assertIn('return "Librarian"', users_list_js)
        self.assertIn('return "Manager"', users_list_js)
        self.assertIn('return "Reader"', users_list_js)
        self.assertIn("const roleBadge = isOwner", users_list_js)
        self.assertIn('<span class="pill pill--owner">Owner</span>', users_list_js)
        self.assertIn('class="user-row__identity"', users_list_js)
        self.assertIn('class="user-row__role"', users_list_js)
        self.assertIn('class="user-row__last-login"', users_list_js)
        self.assertIn('class="user-row__memberships"', users_list_js)
        self.assertIn('class="user-row__badge-list"', users_list_js)
        self.assertIn('class="users-header"', users_list_js)
        self.assertIn("Groups / Curates", users_list_js)
        self.assertIn('aria-label="${escapeHtml(editLabel)}"', users_list_js)
        self.assertIn('class="icon-button"', users_list_js)
        self.assertIn(">edit</span>", users_list_js)
        self.assertNotIn("ownerBadge", users_list_js)
        self.assertNotIn("${escapeHtml(username)}", users_list_js)
        self.assertNotIn('href="${escapeHtml(editHref)}">Edit</a>', users_list_js)
        self.assertNotIn("user-row__column-label", users_list_js)

        self.assertIn('from "../ui/groups.js"', library_list_js)
        self.assertIn('from "../ui/cover_previews.js"', library_list_js)
        self.assertIn('from "../ui/breadcrumbs.js"', library_list_js)
        self.assertIn('from "./prose.js"', library_list_js)
        self.assertIn('from "../auth.js"', library_list_js)
        self.assertIn("canManageLibrary(me)", library_list_js)
        self.assertIn("patchJSON", library_list_js)
        self.assertIn("renderGroupBadge(group, { compact: true })", library_list_js)
        self.assertIn("renderCoverPreviewStrip(author.preview_books", library_list_js)
        self.assertIn("renderCoverPreviewStrip(series.preview_books", library_list_js)
        self.assertNotIn("renderAuthorProse(author)", library_list_js)
        self.assertNotIn("renderSeriesProse(series)", library_list_js)
        self.assertIn('include_preview_books: "true"', library_list_js)
        self.assertEqual(library_list_js.count('include_preview_books: "true"'), 2)
        self.assertIn("function publishedYear", library_list_js)
        self.assertIn("function compactSubtitle", library_list_js)
        self.assertIn("const DEFAULT_PAGE_SIZE = 20", library_list_js)
        self.assertIn("const PAGE_SIZE_OPTIONS = [20, 30, 40, 50]", library_list_js)
        self.assertIn('const VIEWS = new Set(["books", "authors", "series", "author"])', library_list_js)
        self.assertIn('const TAB_VIEWS = new Set(["books", "authors", "series"])', library_list_js)
        self.assertIn("function renderTags", library_list_js)
        self.assertIn("function renderGroups", library_list_js)
        self.assertIn("function visibleBookCountLabel", library_list_js)
        self.assertIn('return `${value} ${value === 1 ? "Book" : "Books"}`', library_list_js)
        self.assertNotIn("visible ${value", library_list_js)
        self.assertNotIn("visible book", library_list_js)
        self.assertIn("function renderAuthors", library_list_js)
        self.assertIn("function renderSeries", library_list_js)
        self.assertIn("libraryBookDetailHref(b.id, context)", library_list_js)
        self.assertIn("canonicalLibraryParams(state", library_list_js)
        self.assertIn("libraryContextHref", library_list_js)
        self.assertIn("function activeBookBreadcrumbContext", library_list_js)
        self.assertIn("function rangeText", library_list_js)
        self.assertIn('return "Showing 0 of 0"', library_list_js)
        self.assertIn("`Showing ${start}-${end} of ${count}`", library_list_js)
        self.assertIn("function apiUrlForState", library_list_js)
        self.assertIn("function renderFilterSummary", library_list_js)
        self.assertIn("function loadActiveFilterContext", library_list_js)
        self.assertIn("function beginContextEdit", library_list_js)
        self.assertIn("async function saveActiveContext", library_list_js)
        self.assertIn('urlWithParams("/api/v1/library/books/"', library_list_js)
        self.assertIn('urlWithParams("/api/v1/library/authors/"', library_list_js)
        self.assertIn('urlWithParams("/api/v1/library/series/"', library_list_js)
        self.assertIn('fetchJSON(`/api/v1/library/${kind === "author" ? "authors" : "series"}/${encodeURIComponent(id)}/`)', library_list_js)
        self.assertIn('patchJSON(\n        `/api/v1/library/${filter.kind === "author" ? "authors" : "series"}/${encodeURIComponent(filter.id)}/`', library_list_js)
        self.assertIn("? { name, biography: prose }", library_list_js)
        self.assertIn(": { name, summary: prose }", library_list_js)
        self.assertIn('page: state.page', library_list_js)
        self.assertIn('page_size: state.pageSize', library_list_js)
        self.assertIn("author: state.authorId", library_list_js)
        self.assertIn("series: state.seriesId", library_list_js)
        self.assertIn(
            'ordering: state.preservedParams.ordering || (state.seriesId ? "series_index" : "")',
            library_list_js,
        )
        self.assertIn("function locationParamsForState", library_list_js)
        self.assertIn("function activeFilter", library_list_js)
        self.assertIn("function syncBreadcrumbs", library_list_js)
        self.assertIn("setBreadcrumbs([", library_list_js)
        self.assertIn('{ label: "Library", href: "/library/" }', library_list_js)
        self.assertIn('{ label: "Books", current: true }', library_list_js)
        self.assertIn('{ label: "Authors", current: true }', library_list_js)
        self.assertIn('{ label: "Series", current: true }', library_list_js)
        self.assertIn('{ label: "Authors", href: "/library/?view=authors" }', library_list_js)
        self.assertIn('{ label: "Series", href: "/library/?view=series" }', library_list_js)
        self.assertIn("state.authorName || state.authorId", library_list_js)
        self.assertIn("state.seriesName || state.seriesId", library_list_js)
        self.assertIn("syncBreadcrumbs();", library_list_js)
        self.assertIn('const activeTabView = activeFilter() ? "books" : state.view', library_list_js)
        self.assertNotIn('data-action="clear-library-filter"', library_list_js)
        self.assertNotIn("author_name", library_list_js)
        self.assertNotIn("series_name", library_list_js)
        self.assertNotIn('from: "author"', library_list_js)
        self.assertNotIn('from: "series"', library_list_js)
        self.assertIn("state.page = 1", library_list_js)
        self.assertIn('pageSizeSelect.addEventListener("change"', library_list_js)
        self.assertIn("state.page += 1", library_list_js)
        self.assertIn("state.page = Math.max(1, state.page - 1)", library_list_js)
        self.assertIn("for (const tab of viewTabs)", library_list_js)
        self.assertIn('tab.addEventListener("click"', library_list_js)
        self.assertIn('data-action="browse-author"', library_list_js)
        self.assertIn('data-action="browse-series"', library_list_js)
        self.assertIn('title="View Books by ${escapeHtml(name)}"', library_list_js)
        self.assertIn('aria-label="View Books by ${escapeHtml(name)}"', library_list_js)
        self.assertIn('title="View Books in ${escapeHtml(name)}"', library_list_js)
        self.assertIn('aria-label="View Books in ${escapeHtml(name)}"', library_list_js)
        self.assertIn('class="library-browse-row__main"', library_list_js)
        self.assertIn('class="library-browse-row__primary"', library_list_js)
        self.assertNotIn('class="library-browse-row__prose"', library_list_js)
        self.assertIn("renderCoverPreviewStrip(author.preview_books", library_list_js)
        self.assertIn("renderCoverPreviewStrip(series.preview_books", library_list_js)
        self.assertIn('bookHref: (book) => libraryBookDetailHref(book && book.id, { kind: "author", id })', library_list_js)
        self.assertIn('bookHref: (book) => libraryBookDetailHref(book && book.id, { kind: "series", id })', library_list_js)
        self.assertNotIn(">View books</button>", library_list_js)
        self.assertIn('source.closest(\'[data-action="toggle-library-prose"]\')', library_list_js)
        self.assertIn("toggleProseBlock(proseToggle, filterSummaryEl)", library_list_js)
        self.assertIn('source.closest(\'[data-action="browse-author"]\')', library_list_js)
        self.assertIn('source.closest(\'[data-action="browse-series"]\')', library_list_js)
        self.assertIn("state.authorId = authorButton.getAttribute", library_list_js)
        self.assertIn("state.authorBiography = payload && payload.biography", library_list_js)
        self.assertIn("state.authorName = payload && payload.name", library_list_js)
        self.assertIn("state.seriesId = seriesButton.getAttribute", library_list_js)
        self.assertIn("state.seriesSummary = payload && payload.summary", library_list_js)
        self.assertIn("state.seriesName = payload && payload.name", library_list_js)
        self.assertIn('state.contextStatus = "Saved."', library_list_js)
        self.assertIn("function safeContextSaveError(error)", library_list_js)
        self.assertIn('typeof error.body === "object"', library_list_js)
        self.assertIn(".slice(0, 240)", library_list_js)
        self.assertIn('return "Failed to save changes."', library_list_js)
        self.assertIn("state.contextError = safeContextSaveError(e)", library_list_js)
        self.assertNotIn("state.contextError = extractApiErrorMessage(e)", library_list_js)
        self.assertNotIn("author.description", library_list_js)
        self.assertNotIn("author.summary", library_list_js)
        self.assertNotIn("series.description", library_list_js)
        self.assertNotIn("series.biography", library_list_js)
        self.assertIn("replaceCurrentLocation()", library_list_js)
        self.assertIn('source.closest(\'[data-action="edit-library-context"]\')', library_list_js)
        self.assertIn('source.closest(\'[data-action="cancel-library-context-edit"]\')', library_list_js)
        self.assertIn('source.closest(\'[data-action="save-library-context"]\')', library_list_js)
        self.assertIn('state.view = "books"', library_list_js)
        self.assertIn('state.view = VIEWS.has(view) ? view : "books"', library_list_js)
        self.assertIn("payload && payload.next", library_list_js)
        self.assertIn("payload && payload.previous", library_list_js)
        self.assertIn("window.history.pushState", library_list_js)
        self.assertIn("window.history.replaceState", library_list_js)
        self.assertIn("mountCovers(resultsEl)", library_list_js)
        self.assertIn('class="library-browse-row"', library_list_js)
        self.assertIn('class="library-browse-row__title"', library_list_js)
        self.assertIn("author.book_count", library_list_js)
        self.assertIn("series.book_count", library_list_js)
        self.assertIn("</div>\n          ${previews}", library_list_js)
        self.assertIn('class="library-row"', library_list_js)
        self.assertIn('class="library-row__title"', library_list_js)
        self.assertIn('class="library-row__meta"', library_list_js)
        self.assertIn('class="library-row__tags"', library_list_js)
        self.assertIn(">Tags</span>", library_list_js)
        self.assertIn("b.publisher", library_list_js)
        self.assertIn("b.published_date", library_list_js)
        self.assertIn("libraryBookDetailHref(b.id, context)", library_list_js)
        self.assertNotIn("function bookFileHtml", library_list_js)
        self.assertNotIn("Download", library_list_js)
        self.assertNotIn("download_url", library_list_js)
        self.assertNotIn("Language:", library_list_js)
        self.assertNotIn("Genre", library_list_js)
        self.assertNotIn("nextUrl", library_list_js)
        self.assertNotIn("prevUrl", library_list_js)

        self.assertIn("export function renderContextProseBlock", library_prose_js)
        self.assertIn("export function renderLibraryContext", library_prose_js)
        self.assertIn('if (!prose) return ""', library_prose_js)
        self.assertIn('class="library-context__prose"', library_prose_js)
        self.assertIn('data-action="toggle-library-prose"', library_prose_js)
        self.assertIn('aria-controls="${escapeHtml(proseId)}"', library_prose_js)
        self.assertIn('aria-expanded="false"', library_prose_js)
        self.assertIn(">Show More</button>", library_prose_js)
        self.assertIn("toggleProseBlock", library_prose_js)
        self.assertIn('target.classList.toggle("is-expanded", nextExpanded)', library_prose_js)
        self.assertIn('button.textContent = nextExpanded ? "Show Less" : "Show More"', library_prose_js)
        self.assertIn("${escapeHtml(prose)}", library_prose_js)
        self.assertIn('data-action="edit-library-context"', library_prose_js)
        self.assertIn('data-action="save-library-context"', library_prose_js)
        self.assertIn('data-action="cancel-library-context-edit"', library_prose_js)
        self.assertNotIn('data-action="clear-library-filter"', library_prose_js)
        self.assertNotIn(">Clear</button>", library_prose_js)
        self.assertIn('name="library-context-name"', library_prose_js)
        self.assertIn('name="library-context-prose"', library_prose_js)
        self.assertIn("Biography", library_list_js)
        self.assertIn("Summary", library_list_js)
        self.assertNotIn("Description", library_prose_js)
        self.assertNotIn("renderAuthorProse", library_prose_js)
        self.assertNotIn("renderSeriesProse", library_prose_js)
        self.assertNotIn("description", library_prose_js)

        self.assertIn("export function pathWithParams", library_navigation_js)
        self.assertIn("export function libraryContextHref", library_navigation_js)
        self.assertIn("export function libraryBookDetailHref", library_navigation_js)
        self.assertIn("export function canonicalLibraryParams", library_navigation_js)
        self.assertIn("export function bookDetailContextFromSearch", library_navigation_js)
        self.assertIn('return pathWithParams("/library/", {', library_navigation_js)
        self.assertIn('view: "author"', library_navigation_js)
        self.assertIn('view: "series"', library_navigation_js)
        self.assertIn('return pathWithParams(base, { view: "books" })', library_navigation_js)
        self.assertIn('if (state.page && state.page !== 1) params.page = state.page', library_navigation_js)
        self.assertIn("state.pageSize !== defaultPageSize", library_navigation_js)
        self.assertIn('params.view = "author"', library_navigation_js)
        self.assertIn('params.view = "books"', library_navigation_js)
        self.assertIn('if (state.q) params.q = state.q', library_navigation_js)
        self.assertIn('if (view === "author")', library_navigation_js)
        self.assertIn('if (view === "series")', library_navigation_js)
        self.assertNotIn("author_name", library_navigation_js)
        self.assertNotIn("series_name", library_navigation_js)
        self.assertNotIn('from: "author"', library_navigation_js)
        self.assertNotIn('from: "series"', library_navigation_js)

        self.assertIn("shelfMetadataLine", list_js)
        self.assertIn('from "../ui/cover_previews.js"', list_js)
        self.assertIn("renderCoverPreviewStrip(shelf.preview_books", list_js)
        self.assertIn("actionLabel: `View shelf ${name}`", list_js)
        self.assertIn('class="shelf-list-card__main"', list_js)
        self.assertIn('class="book__title shelf-list-card__title"', list_js)
        self.assertIn('data-shelf-url="${escapeHtml(href)}"', list_js)
        self.assertIn('title="Open shelf ${escapeHtml(name)}"', list_js)
        self.assertIn('href="${escapeHtml(href)}"', list_js)
        self.assertIn("function isInteractiveElement", list_js)
        self.assertIn('closest("a, button, input, select, textarea, label, summary, [role=\'button\'], [role=\'link\']")', list_js)
        self.assertIn("function installShelfCardNavigation", list_js)
        self.assertIn('source.closest("[data-shelf-url]")', list_js)
        self.assertIn("window.location.assign(url)", list_js)
        self.assertIn("installShelfCardNavigation(personal.resultsEl)", list_js)
        self.assertIn("installShelfCardNavigation(shared.resultsEl)", list_js)
        self.assertNotIn("href,", list_js)
        self.assertIn("renderShelfMetadata", view_js)
        self.assertIn("includeVisibility: false", view_js)
        self.assertIn("renderShelfItem", view_js)
        self.assertIn("document.createElement", view_js)
        self.assertNotIn("innerHTML", view_js)
        self.assertNotIn('"Owner type"', view_js)
        self.assertNotIn('"Metadata"', view_js)
        self.assertNotIn('"User:"', view_js)
        self.assertNotIn('"Group:"', view_js)
        self.assertNotIn("profile_id", view_js)
        self.assertNotIn(".email", view_js)
        self.assertIn("shelfMetadataLine", edit_js)
        self.assertIn("shelfMetadataLine", book_edit_shelves_js)
        self.assertIn("shelfMetadataLine", groups_shared_js)
        self.assertNotIn("shelfOwnerChip", list_js)
        self.assertNotIn("shelfOwnerChip", view_js)
        self.assertNotIn("shelfOwnerChip", edit_js)
        self.assertNotIn("shelfOwnerChip", book_edit_shelves_js)
        self.assertNotIn("shelfOwnerChip", groups_shared_js)
