# Generated by Django 6.0.4 on 2026-07-30 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_author_series_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marginalia_sessions', to='library.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marginalia_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bookmark', 'Bookmark'), ('highlight', 'Highlight')], max_length=16)),
                ('cfi', models.TextField(max_length=8192)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('highlight_text', models.TextField(blank=True, default='')),
                ('comment_text', models.TextField(blank=True, default='')),
                ('quote_prefix', models.TextField(blank=True, default='')),
                ('quote_suffix', models.TextField(blank=True, default='')),
                ('highlight_color', models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('purple', 'Purple'), ('orange', 'Orange')], default='', max_length=16)),
                ('profile_version', models.CharField(default='0.1.0', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='marginalia.readingsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cfi', models.TextField(blank=True, default='', max_length=8192)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('progression', models.FloatField(blank=True, null=True)),
                ('profile_version', models.CharField(default='0.1.0', max_length=16)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='marginalia.readingsession')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'archived'])), name='marginalia_session_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'book'), name='marginalia_one_active_session_per_user_book'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='marginalia_completed_session_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'active')), models.Q(('status', 'active'), _negated=True), _connector='OR'), name='marginalia_active_session_has_no_completion'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['session', 'is_deleted', 'created_at'], name='marg_sess_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['session', 'is_deleted', 'updated_at'], name='marg_sess_del_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['bookmark', 'highlight'])), name='marginalia_annotation_kind_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(('cfi', ''), _negated=True), name='marginalia_annotation_has_cfi'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'highlight'), _negated=True), models.Q(('highlight_text', ''), _negated=True), _connector='OR'), name='marginalia_highlight_has_text'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'bookmark'), _negated=True), models.Q(('comment_text', ''), ('highlight_color', ''), ('highlight_text', '')), _connector='OR'), name='marginalia_bookmark_has_no_content'),
        ),
        migrations.AddConstraint(
            model_name='sessionprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progression__isnull', True), models.Q(('progression__gte', 0.0), ('progression__lte', 1.0)), _connector='OR'), name='marginalia_progression_in_unit_interval'),
        ),
    ]
