# Generated by Django 6.0.4 on 2026-07-13 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('listed', 'Listed')], default='private', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelves_created', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelves_owned', to='library.librarygroup')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelves_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_items_added', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='library.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelves.shelf')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_group__isnull', True), ('owner_type', 'user'), ('owner_user__isnull', False)), models.Q(('owner_group__isnull', False), ('owner_type', 'group'), ('owner_user__isnull', True)), _connector='OR'), name='shelf_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='shelfitem',
            constraint=models.UniqueConstraint(fields=('shelf', 'book'), name='unique_shelf_item_shelf_book'),
        ),
    ]
